In [1]:
import pandas as pd
import numpy as np
%matplotlib inline

import sys
sys.path.append('..')
import edhec_risk_kit as erk

In [2]:
hfi = erk.get_hfi_returns()

# 1

In [3]:
erk.var_gaussian(
    hfi.loc['2000':, 'Distressed Securities'],
    level=1
) * 100

3.1430176939280456

# 2

In [4]:
erk.var_gaussian(
    hfi.loc['2000':, 'Distressed Securities'],
    level=1,
    modified=True
) * 100

4.966909110627921

# 3

In [5]:
erk.var_historic(
    hfi.loc['2000':, 'Distressed Securities'],
    level=1
) * 100

4.2642

# 4

equal weights, so 25%, duh

# 5, 6, 7

In [24]:
ind_all = erk.get_ind_returns()
l = ['Books', 'Steel', 'Oil', 'Mines']
ind = ind_all.loc['2013':'2017', l]

In [11]:
er = erk.annualize_rets(ind, 12)
er

Books    0.095312
Steel    0.100716
Oil      0.025275
Mines    0.005136
dtype: float64

In [14]:
cov = ind.cov()

In [19]:
w_msr = erk.msr(riskfree_rate=0.1, expected_returns=er, covariance_matrix=cov)
w_msr

array([0.00000000e+00, 1.00000000e+00, 6.00214323e-16, 7.35522754e-16])

# 8, 9, 10

In [20]:
cov.columns

Index(['Books', 'Steel', 'Oil', 'Mines'], dtype='object')

In [21]:
w_gmv = erk.gmv(cov)
w_gmv

array([0.47707164, 0.        , 0.43410238, 0.08882597])

# 11

In [30]:
ind_2018 = ind_all.loc['2018':'2019', l]  # without 2019-01, that works because it's a period index?

In [33]:
ind_2018

Books   Steel     Oil   Mines
2018-01  0.0449  0.0361  0.0286  0.0357
2018-02 -0.0325 -0.0199 -0.1102 -0.0335
2018-03  0.0031 -0.0586  0.0308 -0.0015
2018-04 -0.0062  0.0366  0.1030 -0.0339
2018-05 -0.0061  0.0562  0.0343  0.0308
2018-06  0.0218 -0.0514  0.0052 -0.0178
2018-07 -0.0417  0.0424  0.0104 -0.0224
2018-08 -0.0447 -0.0323 -0.0295 -0.1075
2018-09 -0.0221 -0.0067  0.0356 -0.0173
2018-10 -0.0666 -0.1161 -0.1206 -0.1032
2018-11  0.0325 -0.0300 -0.0233 -0.0095
2018-12 -0.1535 -0.1478 -0.1325 -0.0706

In [37]:
w_msr

array([0.00000000e+00, 1.00000000e+00, 6.00214323e-16, 7.35522754e-16])

In [44]:
erk.portfolio_vol(w_msr, ind_2018.cov()) * np.sqrt(12)

0.21983988181484201

# 12

In [45]:
erk.portfolio_vol(w_gmv, ind_2018.cov()) * np.sqrt(12)

0.1897385021889827